files:
    include: 'frontend/scss/**/*.s+(a|c)ss'
    ignore:

rules:
    indentation:
        - 2
        - size: 4

    quotes:
        - 1
        - style: double

    # Disabled rules
    property-sort-order: 0
    class-name-format: 0
